### ISSUE TITLE
Worlds tab can sometimes show others local worlds

### ISSUE THREAD

**Issue by liny-fox** [Nytra/ResoniteFixSessionBrowser#1] opened 2023-11-28 03:02 UTC
Best I can provide is this picture, unless you want a full session log file as this happens randomly so getting a "clean" login, see it happen and log out will be near impossible.

![image](https://github.com/Nytra/ResoniteFixSessionBrowser/assets/7400549/1b395925-6361-40a8-adf3-f1b12b7aaa7c)

[CHRIS-LAPTOP - 2023.11.25.49 - 2023-11-27 17_30_14.log](https://github.com/Nytra/ResoniteFixSessionBrowser/files/13482976/CHRIS-LAPTOP.-.2023.11.25.49.-.2023-11-27.17_30_14.log)
(decided to upload the partial log file anyway)

**Comment by Nytra** [comment] 2023-11-28 03:18
I have noticed this myself but have been unsure if this is actually caused by the mod or not.

**Comment by Nytra** [comment] 2023-11-30 09:57
I've had this happen a couple of times to me when I haven't even been using the mod, so I do think it is unrelated to the mod. Maybe it is caused by another mod or maybe it's a problem in the base game. Since there doesn't seem to be anything for me to do here I will be closing this issue.

**Closed as completed by Nytra** 2023-11-30 09:57 UTC
